### PR TITLE
Fix: Scrolling Scope of Major Page

### PR DESCRIPTION
**Pull request by fung-hei-man**
## Description
修改cardList捲動方式

## Github issue
https://github.com/JiaAnTW/NCKU_Trans/issues/67

## Scope
- /

### CODE REVIEW

**Comment by JiaAnTW** [comment]
@fung-hei-man 指向的branch應該要是develop喔～

**Comment by JiaAnTW** [comment]
@fung-hei-man 原本filter的區域在這個版本的PC版變高了。應該要是跟Production一致的`height: 50px`
- production(PC)
image
- PR版本(PC)
image

**Comment by JiaAnTW** [comment]
然後最後commit msg怪怪的，我不確定GUI版本能不能改，如果不行的話幫我下這兩個指令
```
git commit --amend -m "fix: scrolling scope of major page"
git push origin develop -f
```
另外在自己那邊最好還是拆一個新的branch再來開發，like  `fix/scroll` 之類的。不然如果你開發的某個版本沒有要用，下次重新拉`upstream develop`的時候就會比較麻煩

**Comment by fung-hei-man** [comment]
@JiaAnTW Fixed commit message and the height issue. Please check, thanks ^_^

**Comment by JiaAnTW** [comment]
@fung-hei-man I think the fix didn't rebase or edit old commit. It seems that only the new commits are pushed, and the wrong msg still exsist.

**Comment by fung-hei-man** [comment]
switch to another branch for merging

**Pull request closed without merging**
